version: "3"

services:
  grafana:
    image: grafana/grafana:8.4.4
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=GF_USER
      - GF_SECURITY_ADMIN_PASSWORD=GF_PWD
    volumes:
      - ./grafana/provisionning:/etc/grafana/provisionning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    restart: always

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always