version: "3"

services:
  loki:
    image: grafana/loki:2.4.1
    container_name: Grafana-Loki
    hostname: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.4.1
    container_name: Grafana-Promtail
    hostname: promtail
    volumes:
      - ./promtail/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:?Please configure JENKINS_ADMIN_ID in the .env file}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:?Please configure JENKINS_ADMIN_ID in the .env file}
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: Prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml