---
# tasks file for Grafana

- name: Change hostname
  hostname:
    name: DOCKER-TOOLS

- name: Download Grafana repository
  git:
    repo: https://github.com/Projet-Automation-Infra-SI-Ynov/Grafana.git
    dest: '{{ PATH }}'
    version: master

- name: Add Grafana username in docker-compose.yml
  shell: sed -i 's/GF_USER/USER2/g' /home/administrateur/grafana/docker-compose.yml

- name: Add Grafana password in docker-compose.yml
  shell: sed -i 's/GF_PWD/PWD2/g' /home/administrateur/grafana/docker-compose.yml

- name: Add Jenkins IP in prometheus.yml
  shell: sed -i 's/IP_JENKINS/JENKINS2/g' /home/administrateur/grafana/prometheus.yml

- name: Add Registry IP in prometheus.yml
  shell: sed -i 's/IP_REGISTRY/REGISTRY2/g' /home/administrateur/grafana/prometheus.yml

- name: Add backup IP in prometheus.yml
  shell: sed -i 's/IP_BACKUP_SERVER/BACKUP2/g' /home/administrateur/grafana/prometheus.yml

- name: Add k3s-master IP in prometheus.yml
  shell: sed -i 's/IP_K3SMASTER/MASTER2/g' /home/administrateur/grafana/prometheus.yml

- name: Add k3s-worker IP in prometheus.yml
  shell: sed -i 's/IP_K3SWORKER/WORKER2/g' /home/administrateur/grafana/prometheus.yml

- name: Add Graylog IP in prometheus.yml
  shell: sed -i 's/IP_LOG/GRAYLOG/g' /home/administrateur/grafana/prometheus.yml

- name: Add Registry address IP in daemon.json
  shell: sed -i 's/IP_REGISTRY/REGISTRY2/g' /etc/docker/daemon.json

- name: Add line to collect log
  shell: echo "auth,authpriv.* @@GRAYLOG:1514" >> /etc/rsyslog.conf

- name: Restart the rsyslog service
  systemd:
    name: rsyslog
    state: restarted
    masked: no

- name: Deploy Docker Compose Grafana
  docker_compose:
    build: yes
    project_src: /home/administrateur/grafana
    state: present