---
# tasks file for Grafana

- name: Change hostname
  hostname:
    name: DOCKER-TOOLS

- name: Download Grafana repository
  git:
    repo: https://github.com/Projet-Automation-Infra-SI-Ynov/Grafana.git
    dest: '{{ PATH }}'
    version: develop

- name: Add Jenkins IP in prometheus.yml
  shell: sed -i 's/IP_JENKINS/JENKINS2/g' /home/administrateur/grafana/prometheus.yml

- name: Add Registry IP in prometheus.yml
  shell: sed -i 's/IP_REGISTRY/REGISTRY2/g' /home/administrateur/grafana/prometheus.yml

- name: Add Registry IP in daemon.json
  shell: sed -i 's/IP_REGISTRY/REGISTRY2/g' /home/administrateur/grafana/daemon.json

- name: Deploy Docker Compose Grafana
  docker_compose:
    build: yes
    project_src: /home/administrateur/grafana
    state: present

- name: Copy the Docker daemon file
  copy:
    remote_src: yes
    src: /home/administrateur/grafana/daemon.json
    dest: /etc/docker/daemon.json

# - name: Restart the Docker daemon
#   #become: yes
#   #async: 60
#   systemd:
#     #state: reloaded
#     #daemon_reload: yes
#     name: docker
#     state: restarted
#     masked: no
#     #timeout: 60
#     #async: 60
#   #async: 30
#   #poll: 5
#   timeout: 30

# - name: Restart the Docker daemon
#   systemd:
#     name: docker
#     state: restarted
#     masked: no
#   #timeout: 60
#   async: 60

- name: Stop the Docker daemon
  systemd:
    name: docker
    state: stopped
    masked: no

- name: Start the Docker daemon
  systemd:
    name: docker
    state: started
    masked: no