---
# tasks file for Grafana

- name: Change hostname
  hostname:
    name: DOCKER-TOOLS

- name: Download Grafana repository
  git:
    repo: https://github.com/Projet-Automation-Infra-SI-Ynov/Grafana.git
    dest: '{{ PATH }}'
    version: develop

- name: Add Jenkins IP in prometheus.yml
  shell: sed -i 's/IP_JENKINS/JENKINS2/g' /home/administrateur/grafana/prometheus.yml

- name: Add Jenkins IP in prometheus.yml
  shell: sed -i 's/IP_REGISTRY/REGISTRY2/g' /home/administrateur/grafana/prometheus.yml

- name: Deploy Docker Compose Grafana
  docker_compose:
    build: yes
    project_src: /home/administrateur/grafana
    state: present